create public synonym pipelite2_launcher_lock for pipelite2_launcher_lock;
create public synonym pipelite2_process for pipelite2_process;
create public synonym pipelite2_process_audit for pipelite2_process_audit;
create public synonym pipelite2_process_lock for pipelite2_process_lock;
create public synonym pipelite2_schedule for pipelite2_schedule;
create public synonym pipelite2_schedule_audit for pipelite2_schedule_audit;
create public synonym pipelite2_stage for pipelite2_stage;
create public synonym pipelite2_stage_audit for pipelite2_stage_audit;
create public synonym pipelite2_stage_log for pipelite2_stage_log;
