drop table pipelite2_process;
drop table pipelite2_process_audit;
drop table pipelite2_process_lock;
drop table pipelite2_schedule;
drop table pipelite2_schedule_audit;
drop table pipelite2_stage;
drop table pipelite2_stage_log;
drop table pipelite2_internal_error;
drop table pipelite2_service_lock;