drop public synonym pipelite2_process;
drop public synonym pipelite2_process_audit;
drop public synonym pipelite2_process_lock;
drop public synonym pipelite2_schedule;
drop public synonym pipelite2_schedule_audit;
drop public synonym pipelite2_stage;
drop public synonym pipelite2_stage_log;
drop public synonym pipelite2_internal_error;
drop public synonym pipelite2_service_lock;
